[profile.default]
src = 'src'
out = 'out'
test = "test"

optimizer = true
optimizer_runs = 800
fs_permissions = [{ access = "read-write", path = "./"}]

solc_version="0.8.28"

evm_version="cancun"

[fmt]
line_length = 120
tab_width = 4

[rpc_endpoints]

hyperliquid = "https://rpc.hyperliquid.xyz/evm"
local = "http://localhost:8545"